---
name: CI

on:
  pull_request:
  merge_group:

permissions: {}

jobs:
  required-checks:
    name: CI - Required Checks
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Aggregate job checks
        uses: devantler-tech/actions/aggregate-job-checks@1dddb9d8e7f448a5880d05695742b35960da5bb0 # v5.2.0
        with:
          job-results: ""
