name: CI

permissions: {}

on:
  workflow_dispatch:
  pull_request:
  merge_group:

concurrency:
  group: "ci-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ci-required-checks:
    name: CI - Required Checks
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit
      - run: echo "✅ CI - Required Checks — all checks passed."
