name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/reusable-workflows/.github/workflows/publish-dotnet-library.yaml@e173ff69586caa379a77782b947f1b47166f922e # v4.0.1
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
