name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/actions/.github/workflows/publish-dotnet-library.yaml@da153eb43b8333f13094abb151a48dc11e431988 # v13.7.4
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
