name: Publish
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  packages: write

jobs:
  publish:
    uses: devantler-tech/actions/.github/workflows/publish-dotnet-library.yaml@625b7c0cd5ad4a04f9eb7494298c6d0fa44521ef # v11.0.4
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
