name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: devantler-tech/.github/.github/workflows/create-release.yaml@63c59062489edbee907d2a4d5d06f01c57b7d58c # v7.9.0
    with:
      disable-issue-side-effects: true
    permissions:
      contents: write # create releases and tags
      id-token: write # provenance signing
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
