name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions: {}

jobs:
  release:
    uses: devantler-tech/actions/.github/workflows/create-release.yaml@625b7c0cd5ad4a04f9eb7494298c6d0fa44521ef # v11.0.4
    with:
      disable-issue-side-effects: true
    permissions:
      contents: write # create releases and tags
      id-token: write # provenance signing
    secrets:
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
