name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/run-dotnet-tests.yaml@afd34443d79480ef3f114138b558265a21ac8f13 # v2.3.4
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
