name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/run-dotnet-tests.yaml@c46f75962deb2dab6619de8a379b47b929f40d15 # v2.3.0
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
