name: Test .NET solution or project
permissions:
  packages: read
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    uses: devantler-tech/reusable-workflows/.github/workflows/run-dotnet-tests.yaml@5a334687e73feec66012e62db518716a8618417a # v3.0.0
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
